export const tools = [
  {
    name: "Memory Cleaner",
    slug: "mem-cleaner",
    description: "Simple and efficient command-line tool written in Rust for detecting and managing duplicate files in a directory",
    image: "/_static/tools/mem-cleaner-ss.png",
    tags: ["Untility", "Disk", "Memory"],
    technology: ["Rust"],
    isNew: false,
    version: "0.1.1",
    releasedAt: "March 22, 2025",
    updatedAt: "March 22, 2025",
    repoUrl: "https://github.com/balajimalathi/mem_cleaner",
    demoUrl: "#",
    supportUrl: "#",
    live: true
  }, 
  {
    name: "cmdy",
    slug: "cmdy",
    description: "cmdy is a Rust-based CLI tool that helps automate and manage command execution in different directories with predefined command sets.",
    image: "/_static/tools/cmdy-ss.png",
    tags: ["Rust", "CLI", "Automation"],
    technology: ["Rust"],
    isNew: true,
    version: "1.0.0",
    releasedAt: "March 30, 2025",
    updatedAt: "March 30, 2025",
    repoUrl: "https://github.com/balajimalathi/cmdy",
    demoUrl: "#",
    supportUrl: "#",
    live: true
  },
  {
    name: "Flutter Template Generator",
    slug: "flutter-template-generator",
    description: "Flutter Template Generator CLI where users can add features from CLI and create a boiler plate code",
    image: "",
    tags: ["Flutter", "CLI"],
    technology: ["Flutter", "Dart"],
    isNew: false,
    version: "0.1.1",
    releasedAt: "March 22, 2025",
    updatedAt: "March 22, 2025",
    repoUrl: "#",
    demoUrl: "#",
    supportUrl: "#",
    live: false
  },
]
