export const tools = [
  {
    name: "Memory Cleaner",
    slug: "mem-cleaner",
    description: "Simple and efficient command-line tool written in Rust for detecting and managing duplicate files in a directory",
    image: "/_static/tools/mem_cleaner.png",
    tags: ["Untility", "Disk", "Memory"],
    technology: ["Rust"],
    isNew: false,
    version: "0.1.1",
    releasedAt: "March 22, 2025",
    updatedAt: "March 22, 2025",
    repoUrl: "https://github.com/balajimalathi/mem_cleaner",
    demoUrl: "#",
    supportUrl: "#",
    live: true
  },
  {
    name: "cmdy",
    slug: "cmdy",
    description: "cmdy is a Rust-based CLI tool that helps automate and manage command execution in different directories with predefined command sets.",
    image: "/_static/tools/cmdy.png",
    tags: ["Rust", "CLI", "Automation"],
    technology: ["Rust"],
    isNew: true,
    version: "0.1.0",
    releasedAt: "March 30, 2025",
    updatedAt: "March 30, 2025",
    repoUrl: "https://github.com/balajimalathi/cmdy",
    demoUrl: "#",
    supportUrl: "#",
    live: true
  },
  {
    name: "hej",
    slug: "hej",
    description: "hej is a lightweight Go-based CLI tool designed to provide fast command execution,easy integration, and cross-platform binaries without external dependencies.",
    image: "/_static/tools/mem_cleaner.png",
    tags: ["Go", "CLI", "Productivity"],
    technology: ["Go"],
    isNew: true,
    version: "v1.0.5",
    releasedAt: "August 16, 2025",
    updatedAt: "August 16, 2025",
    repoUrl: "https://github.com/balajimalathi/hej",
    demoUrl: "#",
    supportUrl: "#",
    live: true
  },
  {
    name: "Flutter Template Generator",
    slug: "flutter-template-generator",
    description: "Flutter Template Generator CLI where users can add features from CLI and create a boiler plate code",
    image: "",
    tags: ["Flutter", "CLI"],
    technology: ["Flutter", "Dart"],
    isNew: false,
    version: "0.1.1",
    releasedAt: "March 22, 2025",
    updatedAt: "March 22, 2025",
    repoUrl: "#",
    demoUrl: "#",
    supportUrl: "#",
    live: false
  },
]
