export const tools = [
  {
    name: "Code Analyzer",
    slug: "code-analyzer",
    description: "Powerful static code analysis tool that helps identify bugs, vulnerabilities, and code smells in your codebase.",
    image: "/placeholder.svg?height=400&width=600",
    tags: ["Development", "Security", "Quality"],
    isNew: true,
    version: "2.3.0",
    releasedAt: "January 15, 2023",
    updatedAt: "March 10, 2023",
    documentationUrl: "#",
    demoUrl: "#",
    supportUrl: "#"
  },
  {
    name: "Data Visualizer",
    slug: "data-visualizer",
    description: "Interactive data visualization tool that transforms complex datasets into clear, insightful visual representations.",
    image: "/placeholder.svg?height=400&width=600",
    tags: ["Analytics", "Data", "Visualization"],
    isNew: false,
    version: "3.1.2",
    releasedAt: "November 5, 2022",
    updatedAt: "February 20, 2023",
    documentationUrl: "#",
    demoUrl: "#",
    supportUrl: "#"
  },
  {
    name: "API Gateway",
    slug: "api-gateway",
    description: "Secure and scalable API management solution that handles authentication, rate limiting, and request routing.",
    image: "/placeholder.svg?height=400&width=600",
    tags: ["API", "Security", "Infrastructure"],
    isNew: false,
    version: "1.8.5",
    releasedAt: "March 12, 2022",
    updatedAt: "January 8, 2023",
    documentationUrl: "#",
    demoUrl: "#",
    supportUrl: "#"
  },
  {
    name: "Cloud Manager",
    slug: "cloud-manager",
    description: "Comprehensive cloud resource management tool for monitoring, optimizing, and automating your cloud infrastructure.",
    image: "/placeholder.svg?height=400&width=600",
    tags: ["Cloud", "DevOps", "Monitoring"],
    isNew: true,
    version: "2.0.0",
    releasedAt: "February 1, 2023",
    updatedAt: "March 15, 2023",
    documentationUrl: "#",
    demoUrl: "#",
    supportUrl: "#"
  },
  {
    name: "Security Scanner",
    slug: "security-scanner",
    description: "Advanced security scanning tool that detects vulnerabilities in your applications and infrastructure.",
    image: "/placeholder.svg?height=400&width=600",
    tags: ["Security", "Compliance", "Testing"],
    isNew: false,
    version: "4.2.1",
    releasedAt: "October 10, 2022",
    updatedAt: "February 28, 2023",
    documentationUrl: "#",
    demoUrl: "#",
    supportUrl: "#"
  },
  {
    name: "Performance Monitor",
    slug: "performance-monitor",
    description: "Real-time performance monitoring tool for tracking application metrics, identifying bottlenecks, and optimizing performance.",
    image: "/placeholder.svg?height=400&width=600",
    tags: ["Performance", "Monitoring", "Optimization"],
    isNew: false,
    version: "3.5.0",
    releasedAt: "December 5, 2022",
    updatedAt: "March 1, 2023",
    documentationUrl: "#",
    demoUrl: "#",
    supportUrl: "#"
  },
  {
    name: "Database Manager",
    slug: "database-manager",
    description: "Comprehensive database management tool for administering, optimizing, and monitoring your databases.",
    image: "/placeholder.svg?height=400&width=600",
    tags: ["Database", "Admin", "Performance"],
    isNew: false,
    version: "2.7.3",
    releasedAt: "September 18, 2022",
    updatedAt: "January 25, 2023",
    documentationUrl: "#",
    demoUrl: "#",
    supportUrl: "#"
  },
  {
    name: "Deployment Automator",
    slug: "deployment-automator",
    description: "Streamline your deployment process with automated workflows, testing, and rollback capabilities.",
    image: "/placeholder.svg?height=400&width=600",
    tags: ["CI/CD", "DevOps", "Automation"],
    isNew: true,
    version: "1.0.0",
    releasedAt: "March 1, 2023",
    updatedAt: "March 20, 2023",
    documentationUrl: "#",
    demoUrl: "#",
    supportUrl: "#"
  }
]
